### PR TITLE
Added artifacts and Release workflow

### PR DESCRIPTION
**Pull request by RobRoseKnows**
Here's a biggie!

- Added artifacts to Build workflow.
- Added Release workflow to create draft releases and upload files to them.
- Also created a bunch of new and renamed directories.
- Updated README.md and LICENSE to reflect changes.

You'll have to test the Release workflow manually by creating and push a git tag. I did so on my fork and [it works](https://github.com/RobRoseKnows/RimCI/releases/tag/untagged-f1fa9a7f4a3335109bb1).

### CODE REVIEW

**Comment by krafs** [comment]
You've been at work here! I'm impressed. A few questions:
- Should we address the xml-only mods that is the case for most modders? Sure, most of the benefits of CI is building and testing C#-code, but I can see plenty of xml modders liking the automatic release feature.
- And yes, as you mention in a comment, testing is problematic. If a modder sets up a private nuget feed with the full game assemblies, then some testing certainly can be done. But using e.g. the krafs.rimworld.ref nuget will fail as soon as the testing code attempts to call any method in the game. The nuget contains only reference assemblies, so all methods are stripped and empty. Testing can still be done on logic that doesn't venture beyond the mod, of course.
- Is it possible to reference steps and jobs in workflow files other that the currently executing one? I noticed that half of the release workflow is mostly the same as main.

**Comment by RobRoseKnows** [comment]
Thanks!

- XML-only mods should work just fine with this workflow I think. The Defs folder is automatically collected so long as it's not empty. We could probably edit the README to specify how someone can get that working. I actually don't have much modding experience myself yet, so it's probably better if you update that part.
- Yeah, since you created the krafs.rimworld.ref nuget, do you want to create a guide on how someone could do that? Maybe not in this repo though, but we could use GitHub's Package Registry system to create private nuget feeds in another workflow and let people fork it and add their own Rimworld copy.
- It is possible to reference the end of a previous workflow, but artifacts currently can only be downloaded easily from the same workflow, and since that's how I'm storing build stuff, I figured it's best to do a separate workflow.

I'm also thinking of one additional workflow, triggered on release publish that actually uploads the release zip to Steam Workshop as well as updating workshop pages and what not, probably using some of @fluffy-mods [scripts](https://github.com/fluffy-mods/ModReleaseScript). We'll also need to update this to work with 1.1, but I don't really have much modding experience so I was hoping you'd be able to update it.

After all that is done, I want to create a couple things: 
- a version of this repo with only the workflows so that it can be added as a Git submodule with symlinks (I don't actually know if this is possible, I'll need to check).
- a few [GitHub Templates](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/) that people can use to get started on a mod quickly. For many people, it might even let them create a mod entirely inside the browser!

**Comment by krafs** [comment]
I can certainly add in some modding specific help, and the private nuget feed has been on my mind a long time. But I'm currently neck-deep in some other mod project, so I can't put too much time on it right now.

Not sure much would have to change for 1.1 (or 1.2 that is coming any day now). It's basically just up to the modder herself to manually add the LoadFolders they want to the yaml (because they can name them whatever they want).

Fluffys scripts work well, but I'm still not sure how they're supposed to work in a CI-environment. His scripts use SteamWorks.NET, which as far as I know requires a running, logged in steam client.

I've heard some mixed opinions on submodules, but I know very little about them. Would users basically have a dependency on that repo then, instead of forking or copying it in entirely? RimWorld modders are notoriously grumpy about external dependencies :)

Do we want the mod built for both 1.0 and 1.1 (putting the 1.0 assembly in root/Assemblies and 1.1 in root/1.1/Assemblies)?
I'm currently doing this in my other mod LevelUp, compiling both a .NET35 and .NET472 assembly. Don't think anyone is making 1.0-mods anymore, but it would demonstrate how to handle multiversions going forward.

**Comment by RobRoseKnows** [comment]
I think currently `LoadFolders.xml` isn't collected for the workflow so I might need to modify that. I'll take a look at Fluffy's scripts. If I need to modify something or create another action I can do that. Yeah, I would definitely setup this mod to build for both 1.0 and 1.1, so we can demonstrate how to handle multiversions. I saw you already did some changes in that area so I'll take a look.

**Comment by krafs** [comment]
I guess we could parse `LoadFolders.xml` and implicitly collect those folders. That'd be pretty neat. But then we'd have to also handle how RimWorld itself handles default folders. Like, if there's no `LoadFolders.xml` present, it's going to look for e.g. `1.0 `or `1.1` (RimCI now generates a `1.1` during build, and puts the 1.0 assemblies in `RimCI/Assemblies`).

**Pull request merged**
